DOMAIN: 'simple-loads.dev'
MAILER_SENDER: 'no-reply@simple-loads.dev'
SECRET_KEY_BASE: ''
AIRBRAKE_API_KEY: ''
SKYLIGHT_AUTHENTICATION: ''

SMTP_SERVER: ''
SMTP_PORT: ''
SMTP_LOGIN: ''
SMTP_PASSWORD: ''

LOAD_MAILER_RECIPIENTS: 'no-one@test.com'
